### ISSUE TITLE
Example: error: cannot declare variable 'wsStreamClient' to be of abstract type 'WebSocketStreamClient'

### ISSUE THREAD

**Issue by fightforlife** [areve/WebSocketStreamClient#4]
Hi Areve,

this is the only library on the whole internet I could find, which supports MQTT over WSS.

Sadly the example is not working for me, do zou have an idea?

> error: cannot declare variable 'wsStreamClient' to be of abstract type 'WebSocketStreamClient' WebSocketStreamClient wsStreamClient(wsClient, path);
> 
> WebSocketStreamClient.h:8:7: note:   because the following virtual functions are pure within 'WebSocketStreamClient':
> class WebSocketStreamClient : public Client
> 
> esp8266\hardware\esp8266\2.7.1\cores\esp8266/Client.h:37:22: note: 	virtual void Client::flush()
> virtual void flush() = 0;
> 
> exit status 1
> cannot declare variable 'wsStreamClient' to be of abstract type 'WebSocketStreamClient'
>

**Comment by clysss** [comment]
Compiled with esp8266 board version 2.5.0 is OK
With 2.7 => Error

**Comment by clysss** [comment]
I DID THE DIRTY WAY :
OK to compile with 2.7.x (and last pubsibclient) if :
- you remove the patchlib webscocket250 and use instead classical <websocketclient.h> in websocketstreamclient
=> need to modify websocketstreamclient to change declarations to meet client.h
I don't exactly understand why he don't compile as client.h didn't seems to have change btw board version 2.5 (or 2.6.3 who was also working) and now.. But it works.
Have a look to my [fork](http://github.com/clysss/WebSocketStreamClient) for updated code

PS : Areve, you're a genius. You're idea of implementing client.h that way is just beautifull
Thanks

**Comment by areve** [comment]
Sorry, don't have time, nor need to maintain this library. I'm really happy it's helped others though. May clysss's fork live forever!

**Comment by clysss** [comment]
just a question areve : 
when mqtt msg size is over 128b, the WS hang, because of iTxBuffer[128] in websocket.h (websocketclient private var)
Is there a way to overwrite this without modifyng websocket.h (li tried like you did with websocket250 without success : compile is OK but itxbuffer[128] is still used by the parent class)..

**Comment by mer30boy** [comment]
hi clysss
I used the [library forked by you](https://github.com/clysss/WebSocketStreamClient).
I execute your [example ](https://github.com/clysss/WebSocketStreamClient/blob/master/examples/example-mqtt-ws/example-mqtt-ws.ino)in arduino IDE ( Nodemcu ) and mqtt connect succesfully. 
but the "onMqttPublish" function is never executed and  I do not receive any (published) message.
I also tested with my own personalized mqtt broker and the result was similar.

**Comment by clysss** [comment]
Hello,
I don't know why you're having this issue. Could it be linked to the mqtt
server?
(I don't see any error in the example, but remember never used it directly)
I'm using everyday this lib without issue on esp8266.
My code was before on standard port, and working, and just update it to ws
Perhaps give me more info on your environment

**Comment by mer30boy** [comment]
I think this problem is related to pubsubclient's library.
Because when I searched for this problem, I came to the results of the pubsubclient's library.
What version of pubsubclient's Library do you use?

**Comment by clysss** [comment]
2.8.0

**Comment by mer30boy** [comment]
hi
I solved the previous problem by calling this function:
`mqtt.setBufferSize(5000);`
But there is still another problem:
I want to publish a message. If the number of characters in the message is less than 128 characters, everything will work fine.
But if the message length is more than 128 characters, the message will not be sent and the mqtt connection will be disconnected.

This is part of your library's  README.MD:
> <!> IF the size of MQTT MESSAGE is > 128 bytes, the websocket hang
> => add (pubsubclient)   .setBufferSize(512)
> => change in websocket.h iTxBuffer[512]

as I said I set .setBufferSize function. but where is websocket.h file ?

**Comment by clysss** [comment]
In your library files...

**Comment by mer30boy** [comment]
what library ? There is no file as 'websocket.h' in these libraries!
This is a list of files available in libraries:

[PubSubClient](https://github.com/knolleary/pubsubclient) library:
> PubSubClient.cpp
> PubSubClient.h

[WebSocketStreamClient](https://github.com/knolleary/pubsubclient) lib
> WebSocketStreamClient.h

also I don't find 'iTxBuffer' in these files .

**Comment by clysss** [comment]
How to search for a file name?
