### ISSUE TITLE
cannot declare variable 'wsStreamClient' to be of abstract type 'WebSocketStreamClient'

### ISSUE THREAD

**Issue by mer30boy** [areve/WebSocketStreamClient#5]
Hi
I used your example. But the following error occurred

`test:34:23: error: cannot declare variable 'wsStreamClient' to be of abstract type 'WebSocketStreamClient'
 WebSocketStreamClient wsStreamClient(wsClient, path);
                       ^
In file included from C:\Users\...\Desktop\test\test.ino:4:0:
C:\Users\...\Documents\Arduino\libraries\WebSocketStreamClient/WebSocketStreamClient.h:8:7: note:   because the following virtual functions are pure within 'WebSocketStreamClient':
 class WebSocketStreamClient : public Client
       ^
In file included from C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WiFi\src/WiFiClient.h:27:0,
                 from C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WiFi\src/ESP8266WiFi.h:39,
                 from C:\Users\....\Desktop\test\test.ino:1:
C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266/Client.h:37:22: note: 	virtual void Client::flush()
         virtual void flush() = 0;
                      ^
C:\Users\..\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266/Client.h:29:21: note: 	virtual int Client::connect(IPAddress, uint16_t)
         virtual int connect(IPAddress ip, uint16_t port) =0;
                     ^
C:\Users\..\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266/Client.h:38:22: note: 	virtual void Client::stop()
         virtual void stop() = 0;
                      ^
exit status 1
cannot declare variable 'wsStreamClient' to be of abstract type 'WebSocketStreamClient'
`

**Comment by datdonguyen99** [comment]
I got the same error. Could you help me how to fix this error [mer30boy]?
